name: WFG-docker image build and push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
     # - name: Build and push
     #   id: docker_build
     #   uses: docker/build-push-action@v2
     #   with:
      #    push: true
     #     platforms: linux/amd64,linux/arm64
     #     tags: wwffggle/dockertips:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Docker swarm
      uses: wshihadeh/docker-deployment-action@v1
      with:
        remote_docker_host: root@49.0.206.102
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        deployment_mode: docker-swarm
        copy_stack_file: true
        deploy_path: /root/my-deployment
        stack_file_name: docker-compose.yaml
        keep_files: 5
        args: wwffggle/flask-redis
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: deploy to aws
  #       run: |
  #         cd ansible/
  #         pip install ansible
  #         echo ${{ secrets.ANSIBLE_VAULT }} > vault_pass.txt
  #         export ANSIBLE_VAULT_PASSWORD_FILE=vault_pass.txt
  #         ansible-vault decrypt aws.pem
  #         ansible-playbook -i hosts deploy.yml
